// @ts-check
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    // Globally ignored paths (build output, deps, generated files).
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/.next/**",
      "**/out/**",
      "**/node_modules/**",
      "**/coverage/**",
      "**/next-env.d.ts", // generated by Next (triple-slash refs)
    ],
  },
  eslint.configs.recommended,
  // NOTE: using the non-type-checked preset for the scaffold. Type-aware rules
  // (no-floating-promises / no-misused-promises — valuable for the async
  // polling backend) require `parserOptions.projectService`; enable them once
  // the apps with real tsconfigs land (#2/#3/#4).
  ...tseslint.configs.recommended,
  {
    // Config / tooling files run in Node and are not part of the typed build.
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      sourceType: "module",
    },
  },
  // Keep ESLint out of Prettier's lane (formatting is owned by Prettier).
  prettier,
);
